apiVersion: v1
kind: Config
current-context: 'default'
clusters:
  - name: 'default'
    cluster:
      server: ''
users:
  - name: 'default'
    user:
      token: ''
contexts:
  - name: 'default'
    context:
      cluster: 'default'
      user: 'default'
