apiVersion: v1
kind: Config
current-context: ''
clusters:
  - name: ''
    cluster:
      server: ''
users:
  - name: ''
    user:
      token: ''
contexts:
  - name: ''
    context:
      cluster: ''
      user: ''
